[package]
name = "can-yaml-config-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
can-config-rs={git="https://github.com/mu-zero-HYPERLOOP/can-config-rs.git"}
